### ISSUE TITLE
Support for dbt-core 1.3: Missing fields in `MetricSchema` Class

### ISSUE THREAD

**Issue by PaxonF** [preset-io/backend-sdk#157]
In `api/clients/dbt.py` there's a class called `MetricSchema` that's missing two important fields in order to save metrics to Preset.

Please add the following lines to 564 and 565:

```python
calculation_method = fields.String()
expression = fields.String()
```

This prevents the following error: when syncing with dbt:

```shell
% preset-cli --workspaces=https://****.****.app.preset.io/ superset sync dbt-core target/manifest.json --target=local-prod-service-account --profiles=profiles.yml --project=metamap --import-db

https://****.****.app.preset.io/
[15:50:59] INFO     [[15:50:59]] INFO: preset_cli.cli.superset.sync.dbt.databases: Found an existing database, updating databases.py:57
                    it                                                                                                                 
[15:51:00] INFO     [[15:51:00]] INFO: preset_cli.cli.superset.sync.dbt.datasets: Updating dataset                       datasets.py:96
                    model.metamap.verifications 
                                                                                                           
Traceback (most recent call last):
  File "/Users/***/Documents/GitHub/dbt/.venv/bin/preset-cli", line 8, in <module>
    sys.exit(preset_cli())
  File "/Users/***/Documents/GitHub/dbt/.venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/***/Documents/GitHub/dbt/.venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/***/Documents/GitHub/dbt/.venv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/***/Documents/GitHub/dbt/.venv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/***/Documents/GitHub/dbt/.venv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/***/Documents/GitHub/dbt/.venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/***/Documents/GitHub/dbt/.venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/***/Documents/GitHub/dbt/.venv/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/***/Documents/GitHub/dbt/.venv/lib/python3.8/site-packages/preset_cli/cli/superset/main.py", line 118, in new_command
    ctx.invoke(command, *args, **kwargs)
  File "/Users/***/Documents/GitHub/dbt/.venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/***/Documents/GitHub/dbt/.venv/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/***/Documents/GitHub/dbt/.venv/lib/python3.8/site-packages/preset_cli/cli/superset/sync/dbt/command.py", line 171, in dbt_core
    datasets = sync_datasets(
  File "/Users/***/Documents/GitHub/dbt/.venv/lib/python3.8/site-packages/preset_cli/cli/superset/sync/dbt/datasets.py", line 122, in sync_datasets
    "expression": get_metric_expression(name, model_metrics),
  File "/Users/***/Documents/GitHub/dbt/.venv/lib/python3.8/site-packages/preset_cli/cli/superset/sync/dbt/metrics.py", line 36, in get_metric_expression
    type_ = metric["type"]
KeyError: 'type'
```

I'm unsure if this has any effect on the rest of the package (as I'm new to using it), but this was a quick fix for me.

(Btw, would love to contribute to this project if possible, since my team will have a large stake in it going forward. I love what you all are doing with this to make it easy to sync dbt with Preset. One of the best features I've seen in a BI tool. 😄)

**Comment by cwegener** [comment]
I can confirm that adding the missing fields to the `MetricSchema` marshmallow schema fixes the issue. Looks like this got missed from #154

**Comment by betodealmeida** [comment]
Working on it... I had explicitly made all schemas accept new unknown fields:

https://github.com/preset-io/backend-sdk/blob/6ca7b25c1e1511c38cb2ec4869cc0e6d46b746af/src/preset_cli/api/clients/dbt.py#L30-L43

But we're dropping the unknown fields later:

https://github.com/preset-io/backend-sdk/blob/6ca7b25c1e1511c38cb2ec4869cc0e6d46b746af/src/preset_cli/cli/superset/sync/dbt/command.py#L151
