### ISSUE TITLE
syncing dbt exposures fail 

### ISSUE THREAD

**Issue by advincze-hivemq** [preset-io/backend-sdk#206]
using rev `8c7a4b81bd4e1f94aaeb504b278fe7a12ff7e820`

sometimes charts have an outdated "query_context" 

The error goes away if you open the chart and it "updates" itself

this is the error I see:
```bash
preset-cli --workspaces <my workspace>  superset sync dbt target/manifest.json --project=<my_project> --target=prod --exposures-only --exposures models/preset_exposures.yml

Traceback (most recent call last):
  File "/Users/adam/dwh/.venv/bin/preset-cli", line 8, in <module>
    sys.exit(preset_cli())
  File "/Users/adam/dwh/.venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/adam/dwh/.venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/adam/dwh/.venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/adam/dwh/.venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/adam/dwh/.venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/adam/dwh/.venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/adam/dwh/.venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/adam/dwh/.venv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/adam/dwh/.venv/lib/python3.9/site-packages/preset_cli/cli/superset/main.py", line 118, in new_command
    ctx.invoke(command, *args, **kwargs)
  File "/Users/adam/dwh/.venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/adam/dwh/.venv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/adam/dwh/.venv/lib/python3.9/site-packages/preset_cli/cli/superset/sync/dbt/command.py", line 182, in dbt_core
    sync_exposures(client, Path(exposures), datasets, model_map)
  File "/Users/adam/dwh/.venv/lib/python3.9/site-packages/preset_cli/cli/superset/sync/dbt/exposures.py", line 123, in sync_exposures
    "depends_on": get_chart_depends_on(client, chart, model_map),
  File "/Users/adam/dwh/.venv/lib/python3.9/site-packages/preset_cli/cli/superset/sync/dbt/exposures.py", line 34, in get_chart_depends_on
    query_context = json.loads(chart["query_context"])
  File "/Users/adam/.pyenv/versions/3.9.16/lib/python3.9/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
make: *** [models/preset_exposures.yml] Error 1
```

**Comment by Vitor-Avila** [comment]
Hey @advincze-hivemq,

I managed to repro this scenario, and I believe I have found the root-cause for this issue. When you import a chart, the YAML file doesn't include the `query_context` value, so this information is initially set as `null` to the chart, and then gets populated once the chart is loaded in Explore.  This scenario causes [this line](https://github.com/preset-io/backend-sdk/blob/main/src/preset_cli/cli/superset/sync/dbt/exposures.py#L34) to break.

I'm working on a PR to address this scenario. 

Thanks for reporting this.

**Comment by Vitor-Avila** [comment]
I have a potential fix here: https://github.com/preset-io/backend-sdk/pull/221

**Comment by Vitor-Avila** [comment]
I just merged https://github.com/preset-io/backend-sdk/pull/221, so going to close this issue. @advincze-hivemq let me know if you still face issues after upgrading the CLI based on the repository. I'm going to work on releasing a new version in PyPI next week.
