### ISSUE TITLE
Problem with dbt sync: database field could not be null

### ISSUE THREAD

**Issue by mishga98** [preset-io/backend-sdk#240]
Have a good day!
I faced the following problem during my attempts to sync with dbt project. 
What command I use: `superset-cli -u admin -p admin http://localhost:8088  sync dbt-core dbt_project.yml`
What result I got: 
 `Traceback (most recent call last):
  File "/home/ponomarevmo@comandor.local/.local/bin/superset-cli", line 8, in <module>
    sys.exit(superset_cli())
  File "/home/ponomarevmo@comandor.local/.local/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/ponomarevmo@comandor.local/.local/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/ponomarevmo@comandor.local/.local/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ponomarevmo@comandor.local/.local/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ponomarevmo@comandor.local/.local/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ponomarevmo@comandor.local/.local/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/ponomarevmo@comandor.local/.local/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ponomarevmo@comandor.local/.local/lib/python3.9/site-packages/preset_cli/cli/superset/sync/dbt/command.py", line 154, in dbt_core
    models.append(model_schema.load(config))
  File "/home/ponomarevmo@comandor.local/.local/lib/python3.9/site-packages/marshmallow/schema.py", line 722, in load
    return self._do_load(
  File "/home/ponomarevmo@comandor.local/.local/lib/python3.9/site-packages/marshmallow/schema.py", line 909, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'database': ['Field may not be null.']}
`
Probably I have some mistakes in my model, but I already tried different parameters and specifying database too, I guess it is not the cause. 
I use 2.1.1 superset version. Please, help me!

**Comment by Vitor-Avila** [comment]
Hey @mishga98, 

Could you confirm if you're still impacted by this issue?
