### ISSUE TITLE
superset-cli does not work with superset 3.0.0

### ISSUE THREAD

**Issue by Laxdal** [preset-io/backend-sdk#244]
Looks like `import-assets` , `export-assets`  and `sync` commands in `superset-cli (0.2.8)` do not work with superset version `3.0.0`
Tried it with both basic authentication and jwt. Works on 2.1.0 but fails on 3.0.0.

Sample command:
superset-cli --jwt-token {jwt_token} --loglevel debug {HOST} sync native ./

The error 

`During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/fridrikkarason/.pyenv/versions/local-dev/bin/superset-cli", line 8, in <module>
    sys.exit(superset_cli())
  File "/Users/fridrikkarason/.pyenv/versions/local-dev/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/fridrikkarason/.pyenv/versions/local-dev/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/fridrikkarason/.pyenv/versions/local-dev/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/fridrikkarason/.pyenv/versions/local-dev/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/fridrikkarason/.pyenv/versions/local-dev/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/fridrikkarason/.pyenv/versions/local-dev/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/fridrikkarason/.pyenv/versions/local-dev/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/fridrikkarason/.pyenv/versions/local-dev/lib/python3.9/site-packages/preset_cli/cli/superset/sync/native/command.py", line 239, in native
    import_resources(contents, client, overwrite)
  File "/Users/fridrikkarason/.pyenv/versions/local-dev/lib/python3.9/site-packages/backoff/_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
  File "/Users/fridrikkarason/.pyenv/versions/local-dev/lib/python3.9/site-packages/preset_cli/cli/superset/sync/native/command.py", line 366, in import_resources
    client.import_zip("assets", buf, overwrite=overwrite)
  File "/Users/fridrikkarason/.pyenv/versions/local-dev/lib/python3.9/site-packages/preset_cli/api/clients/superset.py", line 742, in import_zip
    payload = response.json()
  File "/Users/fridrikkarason/.pyenv/versions/local-dev/lib/python3.9/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

When using jwt-token, line 736 in superset.py returns a response object that contains HTML (authentication failed) so it fails in line 742 when trying to extract json

When using basic auth it fails even earlier

`
[15:56:00] DEBUG    [[15:56:00]] DEBUG: urllib3.connectionpool: Starting new HTTP connection (1):        connectionpool.py:228
                    localhost:8090
[15:56:01] DEBUG    [[15:56:01]] DEBUG: urllib3.connectionpool: http://localhost:8090/ "GET /login/       connectionpool.py:456
                    HTTP/1.1" 200 51619
           DEBUG    [[15:56:01]] DEBUG: urllib3.connectionpool: http://localhost:8090/ "POST /login/      connectionpool.py:456
                    HTTP/1.1" 302 201
           DEBUG    [[15:56:01]] DEBUG: urllib3.connectionpool: http://localhost:8090/ "GET /login/       connectionpool.py:456
                    HTTP/1.1" 200 51620
           DEBUG    [[15:56:01]] DEBUG: preset_cli.api.clients.superset: GET                                   superset.py:433
                    http://localhost:8090/api/v1/database/?q=(filters:!(),order_column:changed_on_delta_humani
                    zed,order_direction:desc,page:0,page_size:100)
           DEBUG    [[15:56:01]] DEBUG: urllib3.connectionpool: http://localhost:8090/ "GET               connectionpool.py:456
                    /api/v1/database/?q=(filters:!(),order_column:changed_on_delta_humanized,order_direc
                    tion:desc,page:0,page_size:100) HTTP/1.1" 401 39
           DEBUG    [[15:56:01]] DEBUG: urllib3.connectionpool: Starting new HTTP connection (2):        connectionpool.py:228
                    localhost:8090
[15:56:03] DEBUG    [[15:56:03]] DEBUG: urllib3.connectionpool: http://localhost:8090/ "GET /login/       connectionpool.py:456
                    HTTP/1.1" 200 51620
           DEBUG    [[15:56:03]] DEBUG: urllib3.connectionpool: http://localhost:8090/ "POST /login/      connectionpool.py:456
                    HTTP/1.1" 302 201
           DEBUG    [[15:56:03]] DEBUG: urllib3.connectionpool: http://localhost:8090/ "GET /login/
           
`

**Comment by Laxdal** [comment]
```
127.0.0.1 - - [26/Sep/2023:13:45:37 +0000] "POST /api/v1/assets/import HTTP/1.1" 308 273 "-" "python-requests/2.31.0"
2023-09-26 13:45:38,035:INFO:flask_wtf.csrf:The CSRF session token is missing.
Refresh CSRF token error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask_wtf/csrf.py", line 261, in protect
    validate_csrf(self._get_csrf_token())
  File "/usr/local/lib/python3.8/site-packages/flask_wtf/csrf.py", line 103, in validate_csrf
    raise ValidationError("The CSRF session token is missing.")
wtforms.validators.ValidationError: The CSRF session token is missing.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/usr/local/lib/python3.8/site-packages/flask_wtf/csrf.py", line 229, in csrf_protect
    self.protect()
  File "/usr/local/lib/python3.8/site-packages/flask_wtf/csrf.py", line 264, in protect
    self._error_response(e.args[0])
  File "/usr/local/lib/python3.8/site-packages/flask_wtf/csrf.py", line 307, in _error_response
    raise CSRFError(reason)
flask_wtf.csrf.CSRFError: 400 Bad Request: The CSRF session token is missing.
2023-09-26 13:45:38,035:WARNING:superset.views.base:Refresh CSRF token error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask_wtf/csrf.py", line 261, in protect
    validate_csrf(self._get_csrf_token())
  File "/usr/local/lib/python3.8/site-packages/flask_wtf/csrf.py", line 103, in validate_csrf
    raise ValidationError("The CSRF session token is missing.")
wtforms.validators.ValidationError: The CSRF session token is missing.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/usr/local/lib/python3.8/site-packages/flask_wtf/csrf.py", line 229, in csrf_protect
    self.protect()
  File "/usr/local/lib/python3.8/site-packages/flask_wtf/csrf.py", line 264, in protect
    self._error_response(e.args[0])
  File "/usr/local/lib/python3.8/site-packages/flask_wtf/csrf.py", line 307, in _error_response
    raise CSRFError(reason)
flask_wtf.csrf.CSRFError: 400 Bad Request: The CSRF session token is missing.
```

**Comment by Laxdal** [comment]
setting `WTF_CSRF_ENABLED = False` had no affect

**Comment by Laxdal** [comment]
Sample command along with logs from `3.0.0` vs. `2.1.0`
`superset-cli -u admin -p admin --loglevel debug http://localhost:8089 import-assets ./  --overwrite`
`3.0.0`
```
127.0.0.1 - - [26/Sep/2023:14:41:30 +0000] "GET /superset/welcome/ HTTP/1.1" 302 201 "http://localhost:8088" "Apache Superset Client (0.2.8)"
127.0.0.1 - - [26/Sep/2023:14:41:31 +0000] "GET /login/ HTTP/1.1" 200 51492 "http://localhost:8088" "Apache Superset Client (0.2.8)"
127.0.0.1 - - [26/Sep/2023:14:41:31 +0000] "GET /api/v1/database/?q=(filters:!(),order_column:changed_on_delta_humanized,order_direction:desc,page:0,page_size:100) HTTP/1.1" 401 39 "http://localhost:8088" "Apache Superset Client (0.2.8)"
127.0.0.1 - - [26/Sep/2023:14:41:31 +0000] "GET /login/ HTTP/1.1" 200 51490 "http://localhost:8088" "Apache Superset Client (0.2.8)"
127.0.0.1 - - [26/Sep/2023:14:41:31 +0000] "POST /login/ HTTP/1.1" 302 189 "http://localhost:8088" "Apache Superset Client (0.2.8)"
127.0.0.1 - - [26/Sep/2023:14:41:31 +0000] "GET / HTTP/1.1" 302 223 "http://localhost:8088" "Apache Superset Client (0.2.8)"
2023-09-26 14:41:31,722:WARNING:root:Class 'werkzeug.local.LocalProxy' is not mapped
127.0.0.1 - - [26/Sep/2023:14:41:31 +0000] "GET /superset/welcome/ HTTP/1.1" 302 201 "http://localhost:8088" "Apache Superset Client (0.2.8)"
127.0.0.1 - - [26/Sep/2023:14:41:31 +0000] "GET /login/ HTTP/1.1" 200 51485 "http://localhost:8088" "Apache Superset Client (0.2.8)"
127.0.0.1 - - [26/Sep/2023:14:41:31 +0000] "GET /api/v1/database/?q=(filters:!(),order_column:changed_on_delta_humanized,order_direction:desc,page:0,page_size:100) HTTP/1.1" 401 39 "http://localhost:8088" "Apache Superset Client (0.2.8)"
127.0.0.1 - - [26/Sep/2023:14:41:32 +0000] "GET /login/ HTTP/1.1" 200 51490 "http://localhost:8088" "Apache Superset Client (0.2.8)"
127.0.0.1 - - [26/Sep/2023:14:41:32 +0000] "POST /login/ HTTP/1.1" 302 189 "http://localhost:8088" "Apache Superset Client (0.2.8)"
127.0.0.1 - - [26/Sep/2023:14:41:32 +0000] "GET / HTTP/1.1" 302 223 "http://localhost:8088" "Apache Superset Client (0.2.8)"
2023-09-26 14:41:32,393:WARNING:root:Class 'werkzeug.local.LocalProxy' is not mapped
127.0.0.1 - - [26/Sep/2023:14:41:32 +0000] "GET /superset/welcome/ HTTP/1.1" 302 201 "http://localhost:8088" "Apache Superset Client (0.2.8)"
127.0.0.1 - - [26/Sep/2023:14:41:32 +0000] "GET /login/ HTTP/1.1" 200 51490 "http://localhost:8088" "Apache Superset Client (0.2.8)"
127.0.0.1 - - [26/Sep/2023:14:41:32 +0000] "GET /api/v1/database/?q=(filters:!(),order_column:changed_on_delta_humanized,order_direction:desc,page:0,page_size:100) HTTP/1.1" 401 39 "http://localhost:8088" "Apache Superset Client (0.2.8)"
127.0.0.1 - - [26/Sep/2023:14:41:32 +0000] "GET /login/ HTTP/1.1" 200 51488 "http://localhost:8088" "Apache Superset Client (0.2.8)"
127.0.0.1 - - [26/Sep/2023:14:41:32 +0000] "POST /login/ HTTP/1.1" 302 189 "http://localhost:8088" "Apache Superset Client (0.2.8)"
127.0.0.1 - - [26/Sep/2023:14:41:33 +0000] "GET / HTTP/1.1" 302 223 "http://localhost:8088" "Apache Superset Client (0.2.8)"
2023-09-26 14:41:33,079:WARNING:root:Class 'werkzeug.local.LocalProxy' is not mapped
127.0.0.1 - - [26/Sep/2023:14:41:33 +0000] "GET /superset/welcome/ HTTP/1.1" 302 201 "http://localhost:8088" "Apache Superset Client (0.2.8)"
127.0.0.1 - - [26/Sep/2023:14:41:33 +0000] "GET /login/ HTTP/1.1" 200 51491 "http://localhost:8088" "Apache Superset Client (0.2.8)"
127.0.0.1 - - [26/Sep/2023:14:41:33 +0000] "GET /api/v1/database/?q=(filters:!(),order_column:changed_on_delta_humanized,order_direction:desc,page:0,page_size:100) HTTP/1.1" 401 39 "http://localhost:8088" "Apache Superset Client (0.2.8)"
127.0.0.1 - - [26/Sep/2023:14:41:33 +0000] "GET /login/ HTTP/1.1" 200 51491 "http://localhost:8088" "Apache Superset Client (0.2.8)"
127.0.0.1 - - [26/Sep/2023:14:41:33 +0000] "POST /login/ HTTP/1.1" 302 189 "http://localhost:8088" "Apache Superset Client (0.2.8)"
```

`2.1.0`:
```
127.0.0.1 - - [26/Sep/2023:14:41:39 +0000] "GET /superset/welcome/ HTTP/1.1" 200 27302 "-" "python-requests/2.31.0"
127.0.0.1 - - [26/Sep/2023:14:41:39 +0000] "GET /api/v1/database/?q=(filters:!(),order_column:changed_on_delta_humanized,order_direction:desc,page:0,page_size:100) HTTP/1.1" 200 729 "http://localhost:8089" "Apache Superset Client (0.2.8)"
127.0.0.1 - - [26/Sep/2023:14:41:39 +0000] "GET /api/v1/database/?q=(filters:!(),order_column:changed_on_delta_humanized,order_direction:desc,page:1,page_size:100) HTTP/1.1" 200 519 "http://localhost:8089" "Apache Superset Client (0.2.8)"
127.0.0.1 - - [26/Sep/2023:14:41:39 +0000] "GET /api/v1/database/export/?q=%21%285%29 HTTP/1.1" 200 759 "http://localhost:8089" "Apache Superset Client (0.2.8)"
Updating dbs Trino
2023-09-26 14:41:39,915:INFO:superset.models.helpers:Updating dbs Trino
127.0.0.1 - - [26/Sep/2023:14:41:39 +0000] "POST /api/v1/assets/import/ HTTP/1.1" 200 17 "http://localhost:8089" "Apache Superset Client (0.2.8)"
```

**Comment by oliverlambson** [comment]
Having exactly the same issue, I believe it's to do with redirects because the generated URLs don't have `/` appended when they should and something's happening with the redirects

**Comment by dannyshaw** [comment]
I've had success patching issues to connect to my Superset instance.
 
There central fix was to modify the `UsernamePasswordAuth` to bring in the JWT token into authorisation.
It logs in, gets csrf, fetches a JWT token, and returns the `Authorization: Bearer` header for requests. 

Can PR this as is, but I'm guessing you would wanna implement it cleaner:

```python
class UsernamePasswordAuth(Auth):  # pylint: disable=too-few-public-methods
    """
    Auth to Superset via username/password.
    """

    def __init__(self, baseurl: URL, username: str, password: Optional[str] = None):

        super().__init__()

        self.csrf_token: Optional[str] = None
        self.baseurl = baseurl
        self.username = username
        self.password = password
        self.token = None
        self.auth()

    def get_headers(self) -> Dict[str, str]:
        headers = {}

        if self.token:
            headers["Authorization"] = f"Bearer {self.token}"

        if self.csrf_token:
            headers["X-CSRFToken"] = self.csrf_token

        return headers


    def auth(self) -> None:
        self._login_and_store_csrf()
        self._fetch_and_store_token()


    def _login_and_store_csrf(self) -> None:
        """
        Login to get CSRF token and set cookies.
        """
        data = {"username": self.username, "password": self.password}

        response = self.session.get(self.baseurl / "login/")
        soup = BeautifulSoup(response.text, "html.parser")
        input_ = soup.find("input", {"id": "csrf_token"})
        csrf_token = input_["value"] if input_ else None
        if csrf_token:
            self.session.headers["X-CSRFToken"] = csrf_token
            data["csrf_token"] = csrf_token
            self.csrf_token = csrf_token

        # set cookies
        self.session.post(self.baseurl / "login/", data=data)

    def _fetch_and_store_token(self) -> None:
        """
        Fetch the JWT token to use for headers
        """
        data = {
            "username": self.username,
            "password": self.password,
            "provider":"db",
            "refresh":True,
        }

        api_login_url = self.baseurl / "api/v1/security/login"
        response = self.session.post(api_login_url, json=data)
        self.token = response.json()['access_token']``` 
        
    Note I did originally see similar issues with redirects to the trailing slash url and did make some tweaks to that but I'm not certain they're critical. Possibly. The missing Auth header was the key issue I discovered.
