### ISSUE TITLE
[dbt-core-sync] Not loading variables defined as Jinja in profiles.yml

### ISSUE THREAD

**Issue by mtrentz** [preset-io/backend-sdk#279]
On `0.2.13`, after the MetricFlow update, my environment vars (defined with Jinja) on my `profiles.yml` don't properly load when running `superset-cli sync dbt-core ...`

Here is my profiles yml:

```
much_dbt_warehouse:
  outputs:
    prod:
      dbname: "{{ env_var('DBT_DBNAME') }}"
      host: "{{ env_var('DBT_HOST') }}"
      user: "{{ env_var('DBT_USER') }}"
      pass: "{{ env_var('DBT_PASS') }}"
      port: "{{ env_var('DBT_PORT') | as_number }}"
      threads: "{{ env_var('DBT_THREADS') | as_number }}"
      type: "{{ env_var('DBT_TYPE') }}"
      schema: "{{ env_var('DBT_PROD_SCHEMA') }}"
      meta:
        superset:
          database_name: DWH
  target: prod
```

Here is the error msg:

```
Traceback (most recent call last):
  File "/usr/local/bin/superset-cli", line 8, in <module>
    sys.exit(superset_cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/preset_cli/lib.py", line 148, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/preset_cli/cli/superset/sync/dbt/command.py", line 188, in dbt_core
    mf_dialect = MFSQLEngine(dialect.upper())
  File "/usr/local/lib/python3.9/enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.9/enum.py", line 702, in __new__
    raise ve_exc
ValueError: "{{ ENV_VAR('DBT_TYPE') }}" is not a valid MFSQLEngine
```

**Comment by mtrentz** [comment]
Hopeful fix at #280 :)
