### ISSUE TITLE
DBT metricflow error on standalone superset version

### ISSUE THREAD

**Issue by Santhin** [preset-io/backend-sdk#282]
Packages version:
```  
preset-cli, version 0.2.14   
mf, version 0.205.0
```

Helm chart 
```
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
superset        superset        3               2024-04-15 23:05:41.716187 +0200 CEST   deployed        superset-0.12.9 4.0.0   
```

Values
```
# Override defaults from https://github.com/apache/superset/blob/master/helm/superset/values.yaml

configOverrides:
  secret: |
    SECRET_KEY = ''
  # dbt model/column descriptions into Superset via PUT requests.
  disable_csrf: |
    WTF_CSRF_ENABLED = False

bootstrapScript: |
  #!/bin/bash
  pip3 install snowflake-sqlalchemy
  if [ ! -f ~/bootstrap ]; then echo "Running Superset with uid {{ .Values.runAsUser }}" > ~/bootstrap; fi

```

Example used for boostrapping https://github.com/dbt-labs/jaffle-sl-template/tree/main
Snowflake as a DWH 

Command that creates error
```
superset-cli -u admin -p admin http://localhost:8088 sync dbt ./target/manifest.json --profiles=profiles.yml --target=dev --project=ecommerce --import-db
```

Error log
```
Traceback (most recent call last):
  File "/Users/piotrsierkin/Documents/private/jaffle-sl-template/.venv/bin/superset-cli", line 8, in <module>
    sys.exit(superset_cli())
             ^^^^^^^^^^^^^^
  File "/Users/piotrsierkin/Documents/private/jaffle-sl-template/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/piotrsierkin/Documents/private/jaffle-sl-template/.venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/piotrsierkin/Documents/private/jaffle-sl-template/.venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/piotrsierkin/Documents/private/jaffle-sl-template/.venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/piotrsierkin/Documents/private/jaffle-sl-template/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/piotrsierkin/Documents/private/jaffle-sl-template/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/piotrsierkin/Documents/private/jaffle-sl-template/.venv/lib/python3.11/site-packages/preset_cli/lib.py", line 148, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/piotrsierkin/Documents/private/jaffle-sl-template/.venv/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/piotrsierkin/Documents/private/jaffle-sl-template/.venv/lib/python3.11/site-packages/preset_cli/cli/superset/sync/dbt/command.py", line 224, in dbt_core
    superset_metrics = get_superset_metrics_per_model(og_metrics, sl_metrics)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/piotrsierkin/Documents/private/jaffle-sl-template/.venv/lib/python3.11/site-packages/preset_cli/cli/superset/sync/dbt/metrics.py", line 263, in get_superset_metrics_per_model
    metric_definition = convert_metric_flow_to_superset(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/piotrsierkin/Documents/private/jaffle-sl-template/.venv/lib/python3.11/site-packages/preset_cli/cli/superset/sync/dbt/metrics.py", line 378, in convert_metric_flow_to_superset
    "expression": convert_query_to_projection(sql, dialect),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/piotrsierkin/Documents/private/jaffle-sl-template/.venv/lib/python3.11/site-packages/preset_cli/cli/superset/sync/dbt/metrics.py", line 314, in convert_query_to_projection
    for node, _, _ in metric_expression.walk():
        ^^^^^^^^^^
ValueError: not enough values to unpack (expected 3, got 0)
```

**Comment by Santhin** [comment]
Hey @Vitor-Avila here is the pip list 
`sqlglot                    23.10.0`
```
❯ uv pip list
Package                    Version
-------------------------- ---------
agate                      1.7.1
aiohttp                    3.9.4
aiosignal                  1.3.1
appdirs                    1.4.4
asn1crypto                 1.5.1
attrs                      23.2.0
babel                      2.14.0
backoff                    2.2.1
beautifulsoup4             4.12.3
cachetools                 5.3.3
certifi                    2024.2.2
cffi                       1.16.0
charset-normalizer         3.3.2
click                      8.1.7
colorama                   0.4.6
cryptography               42.0.5
cython                     3.0.10
db-dtypes                  1.2.0
dbt-bigquery               1.7.7
dbt-core                   1.7.11
dbt-extractor              0.5.1
dbt-metricflow             0.6.0
dbt-semantic-interfaces    0.4.4
dbt-snowflake              1.7.3
filelock                   3.13.4
frozenlist                 1.4.1
google-api-core            2.18.0
google-auth                2.29.0
google-cloud-bigquery      3.20.1
google-cloud-core          2.4.1
google-cloud-dataproc      5.9.3
google-cloud-storage       2.16.0
google-crc32c              1.5.0
google-resumable-media     2.7.0
googleapis-common-protos   1.63.0
graphviz                   0.20.3
greenlet                   3.0.3
grpc-google-iam-v1         0.13.0
grpcio                     1.62.1
grpcio-status              1.62.1
halo                       0.0.31
idna                       3.7
importlib-metadata         6.11.0
isodate                    0.6.1
jaraco-classes             3.4.0
jinja2                     3.1.3
jsonschema                 4.21.1
jsonschema-specifications  2023.12.1
keyring                    24.3.1
leather                    0.4.0
log-symbols                0.0.14
logbook                    1.5.3
markdown-it-py             3.0.0
markupsafe                 2.1.5
marshmallow                3.21.1
mashumaro                  3.12
mdurl                      0.1.2
metricflow                 0.205.0
minimal-snowplow-tracker   0.0.2
more-itertools             10.1.0
msgpack                    1.0.8
multidict                  6.0.5
networkx                   3.3
numpy                      1.26.4
packaging                  24.0
pandas                     1.5.3
parsedatetime              2.6
pathspec                   0.11.2
platformdirs               4.2.0
preset-cli                 0.2.14
prison                     0.2.1
prompt-toolkit             3.0.43
proto-plus                 1.23.0
protobuf                   4.25.3
pyarrow                    15.0.2
pyasn1                     0.6.0
pyasn1-modules             0.4.0
pycparser                  2.22
pydantic                   1.10.15
pygments                   2.17.2
pyjwt                      2.8.0
pyopenssl                  24.1.0
python-dateutil            2.8.2
python-graphql-client      0.4.3
python-slugify             8.0.4
pytimeparse                1.1.8
pytz                       2024.1
pyyaml                     6.0.1
rapidfuzz                  3.8.1
referencing                0.34.0
requests                   2.31.0
rich                       13.7.1
rpds-py                    0.18.0
rsa                        4.9
ruamel-yaml                0.17.40
ruamel-yaml-clib           0.2.8
six                        1.16.0
snowflake-connector-python 3.8.1
sortedcontainers           2.4.0
soupsieve                  2.5
spinners                   0.0.24
sqlalchemy                 1.4.52
sqlglot                    23.10.0
sqlparse                   0.4.4
tabulate                   0.9.0
termcolor                  2.4.0
text-unidecode             1.3
tomlkit                    0.12.4
typing-extensions          4.11.0
update-checker             0.18.0
urllib3                    1.26.18
wcwidth                    0.2.13
websockets                 12.0
yarl                       1.9.4
zipp                       3.18.1
```

**Comment by Santhin** [comment]
Python version `pyenv 3.11.6`

**Comment by Vitor-Avila** [comment]
@Santhin yea, likely the failure is due to the `sqlglot` version. Please downgrade it by executing `pip install --upgrade sqlglot==20.7.1` and then trigger the sync again. You can use a newer version as well if desired -- from my tests it starts failing on `23.0.0` so anything below that (and higher than `19`) should work. 

My PR should update the CLI dependencies configuration so that installing the CLI doesn't install latest `sqlglot` versions.

**Comment by Santhin** [comment]
Work as expected downgrading `sqlglot` :bow: @Vitor-Avila

**Comment by Vitor-Avila** [comment]
awesome! I'll close this one then (just merged my PR with an upper bound, and will also eventually add logic to support newer `sqlglot` versions).
