### ISSUE TITLE
sync dbt fails on Athena from version 0.2.12 

### ISSUE THREAD

**Issue by advincze-hivemq** [preset-io/backend-sdk#288]
to provision our models that were built by dbt on AWS Athena we run the following command:

preset-cli superset sync dbt target/manifest.json  --project=<project> --target=prod --disallow-edits --select <model>

in version 0.2.11 everything is ok, 
from version 0.2.12 to the current one we get the following error message: 
```
Traceback (most recent call last):
  File "/Users/adam/src/github.com/hivemq/dwh-core/.venv/bin/preset-cli", line 8, in <module>
    sys.exit(preset_cli())
  File "/Users/adam/src/github.com/hivemq/dwh-core/.venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/adam/src/github.com/hivemq/dwh-core/.venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/adam/src/github.com/hivemq/dwh-core/.venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/adam/src/github.com/hivemq/dwh-core/.venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/adam/src/github.com/hivemq/dwh-core/.venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/adam/src/github.com/hivemq/dwh-core/.venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/adam/src/github.com/hivemq/dwh-core/.venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/adam/src/github.com/hivemq/dwh-core/.venv/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/adam/src/github.com/hivemq/dwh-core/.venv/lib/python3.10/site-packages/preset_cli/cli/superset/main.py", line 117, in new_command
    ctx.invoke(command, *args, **kwargs)
  File "/Users/adam/src/github.com/hivemq/dwh-core/.venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/adam/src/github.com/hivemq/dwh-core/.venv/lib/python3.10/site-packages/preset_cli/lib.py", line 148, in wrapper
    return function(*args, **kwargs)
  File "/Users/adam/src/github.com/hivemq/dwh-core/.venv/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/adam/src/github.com/hivemq/dwh-core/.venv/lib/python3.10/site-packages/preset_cli/cli/superset/sync/dbt/command.py", line 188, in dbt_core
    mf_dialect = MFSQLEngine(dialect.upper())
  File "/Users/adam/.pyenv/versions/3.10.13/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/Users/adam/.pyenv/versions/3.10.13/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: 'ATHENA' is not a valid MFSQLEngine
```

**Comment by rjoelnorgren** [comment]
Similar issue when using with ClickHouse and 0.2.16:
```
preset-cli \
  --workspaces=https://*****.****.app.preset.io/ \
  superset sync dbt-core target/manifest.json \
  --project=*** \
  --target=superset-processing \
  --profiles=profiles.yml \
  --disallow-edits \
  --import-db \
  --select ***

https://*****.****.app.preset.io/
Traceback (most recent call last):
  File "/opt/.venv/bin/preset-cli", line 8, in <module>
    sys.exit(preset_cli())
             ^^^^^^^^^^^^
  File "/opt/.venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/.venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/.venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/.venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/.venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/.venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/.venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/.venv/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/.venv/lib/python3.12/site-packages/preset_cli/cli/superset/main.py", line 117, in new_command
    ctx.invoke(command, *args, **kwargs)
  File "/opt/.venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/.venv/lib/python3.12/site-packages/preset_cli/lib.py", line 148, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/.venv/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/.venv/lib/python3.12/site-packages/preset_cli/cli/superset/sync/dbt/command.py", line 191, in dbt_core
    mf_dialect = MFSQLEngine(dialect.upper())
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 744, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 1158, in __new__
    raise ve_exc
ValueError: 'CLICKHOUSE' is not a valid MFSQLEngine
```

**Comment by Vitor-Avila** [comment]
Hey @advincze-hivemq and @rjoelnorgren,

Could you please confirm the dbt version you're running? Do you have metrics defined using the new semantic model? Or are you using the legacy metric schema?

Thank you!

**Comment by Vitor-Avila** [comment]
Hey @advincze-hivemq,

I just released a new CLI version including a fix that would bypass the MetricFlow dialect enforcement. Could you please update the CLI on your end and let me know if you're still unable to sync?

Thanks!

**Comment by advincze-hivemq** [comment]
Worked thanks
