### ISSUE TITLE
Unable to replace API token in case it's no longer valid 

### ISSUE THREAD

**Issue by Vitor-Avila** [preset-io/backend-sdk#39]
### Description
If the API credentials previously configured with the `preset-cli` are no longer valid, `preset-cli auth --overwrite` won't work properly, preventing users to enter new valid values. 

### How to reproduce the bug
1. Generate an API key.
2. Configure the `preset-cli` to use it. 
3. Delete/deactivate this API key on Superset/Preset.
4. Run `preset-cli auth --overwrite`.

### Expected Results
User can update the key using this command. 

### Actual Results
Below exception is thrown:
```
Traceback (most recent call last):
  File "/home/vavila/.pyenv/versions/preset-cli/bin/preset-cli", line 8, in <module>
    sys.exit(preset_cli())
  File "/home/vavila/.pyenv/versions/3.9.0/envs/preset-cli/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/vavila/.pyenv/versions/3.9.0/envs/preset-cli/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/vavila/.pyenv/versions/3.9.0/envs/preset-cli/lib/python3.9/site-packages/click/core.py", line 1654, in invoke
    super().invoke(ctx)
  File "/home/vavila/.pyenv/versions/3.9.0/envs/preset-cli/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vavila/.pyenv/versions/3.9.0/envs/preset-cli/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/vavila/.pyenv/versions/3.9.0/envs/preset-cli/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/vavila/.pyenv/versions/3.9.0/envs/preset-cli/lib/python3.9/site-packages/preset_cli/cli/main.py", line 144, in preset_cli
    jwt_token = get_access_token(manager_url, api_token, api_secret)
  File "/home/vavila/.pyenv/versions/3.9.0/envs/preset-cli/lib/python3.9/site-packages/preset_cli/auth/lib.py", line 29, in get_access_token
    return payload["payload"]["access_token"]
KeyError: 'payload'
```

**Comment by betodealmeida** [comment]
Fixed in https://github.com/preset-io/backend-sdk/pull/41.
