### ISSUE TITLE
Error when using the children/parent selection method for dbt syncing

### ISSUE THREAD

**Issue by dweaver33** [preset-io/backend-sdk#67]
Running this command (Please note that I removed company sensitive elements):
```
preset-cli --workspaces=https://[REMOVED].app.preset.io/ superset sync dbt target/manifest.json --project=[REMOVED] --target=dev --import-db --disallow-edits --external-url-prefix=[REMOVED] --exposures=models/exposures.yml --select [REMOVED]+
```

Results in the following error:
```
[14:19:52] INFO     [[14:19:52]] INFO: preset_cli.cli.superset.sync.dbt.databases: Found an existing database, updating it                                databases.py:54
Traceback (most recent call last):
  File "/usr/local/bin/preset-cli", line 8, in <module>
    sys.exit(preset_cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/preset_cli/cli/superset/main.py", line 103, in new_command
    ctx.invoke(command, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/preset_cli/cli/superset/sync/dbt/command.py", line 111, in dbt_core
    models = apply_select(models, select, exclude)
  File "/usr/local/lib/python3.9/site-packages/preset_cli/cli/superset/sync/dbt/lib.py", line 349, in apply_select
    *[
  File "/usr/local/lib/python3.9/site-packages/preset_cli/cli/superset/sync/dbt/lib.py", line 350, in <listcomp>
    {model["unique_id"] for model in filter_models(models, condition)}
  File "/usr/local/lib/python3.9/site-packages/preset_cli/cli/superset/sync/dbt/lib.py", line 235, in filter_models
    return filter_plus_operator(models, condition)
  File "/usr/local/lib/python3.9/site-packages/preset_cli/cli/superset/sync/dbt/lib.py", line 291, in filter_plus_operator
    for child_id in model["children"]
KeyError: 'children'
```

CLI Version: `preset-cli                          0.1.0.post1.dev5+gae8587f`
dbt Version: `dbt 1.2.1`

**Comment by dweaver33** [comment]
This error persists when using the parent select method as well.

**Comment by betodealmeida** [comment]
Taking a look!

**Comment by dweaver33** [comment]
To help with troubleshooting: 
OS: MacOS Monterey 12.4
Python: 3.9.13
Running terminal in Rosetta

**Comment by betodealmeida** [comment]
@dweaver33 can you upgrade and try again? I have a tentative fix.

**Comment by dweaver33** [comment]
Hi, this still doesn't seem to work.  For example, running the above command now pushes the first model, but not the children.  Running with the "parent" operator results in the same.  

Here's the preset-cli version I'm running: `0.1.1.post1.dev2+g26b2674`

**Comment by betodealmeida** [comment]
@dweaver33 any chance you could share the `manifest.json` with me privately, or at least the information about the DAG? It's weird that the models have no `children` attributes. I assume you ran `dbt compile` before running the CLI to sync?

**Comment by dweaver33** [comment]
I will send in the morning. And yes, ran compile before syncing.

**Comment by dweaver33** [comment]
Sent to your email.

**Comment by betodealmeida** [comment]
Fixed in https://github.com/preset-io/backend-sdk/pull/92.
